apiVersion: v1
kind: Service
metadata:
  name: {{ include "manager.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "manager.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.flask.port }}
      protocol: TCP
