[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file = /var/run/supervisord.sock

;[inet_http_server]
;port = 9001

[supervisorctl]
serverurl = unix:///var/run/supervisord.sock
;serverurl = http://localhost:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
stdout_logfile=/var/log/sshd.log
stderr_logfile=/var/log/sshd_error.log

[program:motley_cue]
command=%(ENV_VENV_PATH)s/bin/motley_cue_uvicorn
autostart=true
autorestart=true
stdout_logfile=/var/log/motley_cue.log
stderr_logfile=/var/log/motley_cue_error.log
