# Default values for interlink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nodeName: vk-node

interlink:
  enabled: true
  address: http://0.0.0.0
  port: 3000

plugin:
  enabled: false
  address: http://0.0.0.0
  port: 4000

wstunnel:
  enabled: true
  port: 8420
  host: interlink.dev.local
  logLevel: debug
  secret: "h3GywpDrP6gJEdZ6xbJbZZVFmvFZDCa4KcRd"

