FROM almalinux:9

ENV VENV_PATH=/opt/venv

RUN yum install -y openssh-server && \
    yum clean all

# Generate SSH host keys
RUN ssh-keygen -A

RUN python3 -m venv ${VENV_PATH} && \
    ${VENV_PATH}/bin/pip install --upgrade pip && \
    ${VENV_PATH}/bin/pip install motley-cue supervisor

ENV MOTLEY_CUE_CONFIG=${VENV_PATH}/motley_cue.conf
COPY motley_cue.conf ${MOTLEY_CUE_CONFIG}

ENV FEUDAL_ADAPTER_CONFIG=${VENV_PATH}/feudal_adapter.conf
COPY feudal_adapter.conf ${FEUDAL_ADAPTER_CONFIG}

# Copy supervisord configuration
COPY supervisord.conf /etc/supervisord.conf

EXPOSE 22
EXPOSE 8080

ENTRYPOINT ["sh", "-c", "${VENV_PATH}/bin/supervisord -c /etc/supervisord.conf"]
