; supervisord.conf — HPC Pilot managed services
;
; This file is generated by manager/hpc/setup.sh and placed at
;   ~/.hpc-pilot/supervisord.conf
; on the remote HPC node.
;
; Managed programs
; ─────────────────
;   wstunnel   – WebSocket tunnel client connecting back to the K8s cluster.
;
; Variables substituted by setup.sh (shell parameter expansion):
;   WSTUNNEL_SERVER      – public hostname of the K8s-side wstunnel server
;   WSTUNNEL_PORT        – port on the wstunnel server (e.g. 8420)
;   WSTUNNEL_SECRET      – shared bearer-token secret
;   WSTUNNEL_LOCAL_PORT  – local TCP port exposed on this HPC node

[unix_http_server]
file=%(ENV_HOME)s/.hpc-pilot/supervisor.sock

[supervisord]
nodaemon=false
logfile=%(ENV_HOME)s/.hpc-pilot/logs/supervisord.log
logfile_maxbytes=10MB
logfile_backups=3
loglevel=info
pidfile=%(ENV_HOME)s/.hpc-pilot/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix://%(ENV_HOME)s/.hpc-pilot/supervisor.sock

; ── wstunnel client ───────────────────────────────────────────────────────────
;
; Connects to the wstunnel server running in the user's K8s namespace and
; exposes a local TCP port on this HPC node that interLink can reach.
;
; wstunnel client mode:
;   --local-to-remote tcp://0.0.0.0:<LOCAL_PORT>:localhost:<LOCAL_PORT>
;   --wstunnel-server wss://<SERVER>:<PORT>
;   -H "authorization: Bearer <SECRET>"

[program:wstunnel]
command=%(ENV_HOME)s/.hpc-pilot/bin/wstunnel client
    --local-to-remote tcp://0.0.0.0:${WSTUNNEL_LOCAL_PORT}:localhost:${WSTUNNEL_LOCAL_PORT}
    -H "authorization: Bearer ${WSTUNNEL_SECRET}"
    wss://${WSTUNNEL_SERVER}:${WSTUNNEL_PORT}
directory=%(ENV_HOME)s/.hpc-pilot
autostart=true
autorestart=true
startretries=5
startsecs=3
stdout_logfile=%(ENV_HOME)s/.hpc-pilot/logs/wstunnel-stdout.log
stderr_logfile=%(ENV_HOME)s/.hpc-pilot/logs/wstunnel-stderr.log
stdout_logfile_maxbytes=5MB
stderr_logfile_maxbytes=5MB
