user:
  name: ""

ingress:
  enabled: true

wstunnel:
 # 'connectionSecret' is used in wstunnel-client to connect to the server
 # e.g. wstunnel client --restrict-http-upgrade-path-prefix <a-random-string> ws://...
  connectionSecret: "<a-random-string>" 
